/// Flutter icons LoginExample
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LoginExample
///      fonts:
///       - asset: fonts/LoginExample.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LoginExample {
  LoginExample._();

  static const _kFontFam = 'LoginExample';

  static const IconData google_b_hit = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData google_a = const IconData(0xe801, fontFamily: _kFontFam);
}
